/* Generated By:JavaCC: Do not edit this line. CQLParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface CQLParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SELECT = 5;
  /** RegularExpression Id. */
  int STAR = 6;
  /** RegularExpression Id. */
  int FROM = 7;
  /** RegularExpression Id. */
  int WHERE = 8;
  /** RegularExpression Id. */
  int AND = 9;
  /** RegularExpression Id. */
  int OR = 10;
  /** RegularExpression Id. */
  int AVG = 11;
  /** RegularExpression Id. */
  int SUM = 12;
  /** RegularExpression Id. */
  int LPAREN = 13;
  /** RegularExpression Id. */
  int RPAREN = 14;
  /** RegularExpression Id. */
  int EQUALS = 15;
  /** RegularExpression Id. */
  int COMMA = 16;
  /** RegularExpression Id. */
  int LOWER = 17;
  /** RegularExpression Id. */
  int GRATER = 18;
  /** RegularExpression Id. */
  int LESSEREQUAL = 19;
  /** RegularExpression Id. */
  int GRATEREQUAL = 20;
  /** RegularExpression Id. */
  int WINDOW = 21;
  /** RegularExpression Id. */
  int NUMBER = 22;
  /** RegularExpression Id. */
  int STRING = 23;
  /** RegularExpression Id. */
  int QUOTED_STRING = 24;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "<SELECT>",
    "\"*\"",
    "<FROM>",
    "<WHERE>",
    "<AND>",
    "<OR>",
    "<AVG>",
    "<SUM>",
    "\"(\"",
    "\")\"",
    "\"=\"",
    "\",\"",
    "\"<\"",
    "\">\"",
    "\"<=\"",
    "\">=\"",
    "<WINDOW>",
    "<NUMBER>",
    "<STRING>",
    "<QUOTED_STRING>",
  };

}
